# Generated by Django 4.2.10 on 2026-04-14 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_vawcsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=50)),
                ('email_preference', models.CharField(max_length=50)),
                ('new_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alternative_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
