# Generated by Django 4.2.10 on 2026-04-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accountresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountresetrequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='accountresetrequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
