# Generated by Django 4.2.10 on 2026-04-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accountresetrequest_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
