# Generated by Django 4.2.10 on 2026-04-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_healthcareaccount_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareaccount',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lawenforcementaccount',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swdoaccount',
            name='office_assigned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
