# Generated by Django 5.0.1 on 2024-06-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_passkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('host', models.CharField(max_length=250)),
                ('port', models.PositiveBigIntegerField(max_length=10)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
