# Generated by Django 4.2.10 on 2026-04-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_healthcareaccount_city_lawenforcementaccount_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id_picture',
            field=models.ImageField(blank=True, null=True, upload_to='id_pictures/'),
        ),
        migrations.AddField(
            model_name='healthcareaccount',
            name='id_picture',
            field=models.ImageField(blank=True, null=True, upload_to='id_pictures/'),
        ),
        migrations.AddField(
            model_name='lawenforcementaccount',
            name='id_picture',
            field=models.ImageField(blank=True, null=True, upload_to='id_pictures/'),
        ),
        migrations.AddField(
            model_name='swdoaccount',
            name='id_picture',
            field=models.ImageField(blank=True, null=True, upload_to='id_pictures/'),
        ),
    ]
