# Generated by Django 5.0.1 on 2024-06-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='port',
            field=models.PositiveBigIntegerField(),
        ),
    ]
