# Generated by Django 4.2.10 on 2026-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_id_picture_healthcareaccount_id_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='policestations',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
