# Generated by Django 5.0.1 on 2024-06-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_email_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_key', models.CharField(max_length=150)),
                ('secret_key', models.CharField(max_length=150)),
            ],
        ),
    ]
