# Generated by Django 5.0.1 on 2025-02-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_twilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilio',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
