# Generated by Django 5.0.1 on 2025-02-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_twilio_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twilio',
            name='type',
            field=models.CharField(choices=[('local', 'Local'), ('deployed', 'Deployed')], default='local', max_length=20),
        ),
    ]
