# Generated by Django 5.0.1 on 2025-05-22 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_lawenforcementaccount_policestations'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawEnforcementAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('verified', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('station', models.CharField(blank=True, max_length=100, null=True)),
                ('passkey', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
