# Generated by Django 5.0.1 on 2025-05-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_lawenforcementaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawenforcementaccount',
            name='type',
            field=models.CharField(default='law_enforcement', max_length=20),
        ),
    ]
