# Generated by Django 5.2.4 on 2025-07-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_lawenforcementaccount_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twilio',
            old_name='type',
            new_name='account_type',
        ),
    ]
