# Generated by Django 4.2.10 on 2026-03-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='civil_status',
            field=models.CharField(blank=True, default='Single', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent_perpetrator',
            name='civil_status',
            field=models.CharField(blank=True, default='Single', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='civil_status',
            field=models.CharField(blank=True, default='Single', max_length=100, null=True),
        ),
    ]
