# Generated by Django 4.2.10 on 2026-04-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_caseedithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
