# Generated by Django 4.2.10 on 2026-05-07 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0005_case_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_barangay', models.CharField(max_length=255)),
                ('to_barangay', models.CharField(max_length=255)),
                ('to_city', models.CharField(blank=True, max_length=255, null=True)),
                ('to_province', models.CharField(blank=True, max_length=255, null=True)),
                ('to_region', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date_referred', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangay_referrals', to='case.case')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
