# Generated by Django 5.0.1 on 2024-06-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_case_date_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='phone',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
