# Generated by Django 5.2.4 on 2025-07-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0015_lawenforcementreferredcase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LawEnforcementReferredCase',
        ),
    ]
